//
// Generated file, do not edit! Created by nedtool 5.5 from applications/myapplication/TransactionsMsg.msg.
//

#ifndef __TRANSACTIONSMSG_M_H
#define __TRANSACTIONSMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "common/TransportAddress.h"
#include <list>
typedef std::list<int> Transactions;
// }}

/**
 * Class generated from <tt>applications/myapplication/TransactionsMsg.msg:38</tt> by nedtool.
 * <pre>
 * // now we declare the message
 * packet TransactionsMsg
 * {
 *     Transactions transactions;
 *     TransportAddress senderAddress;  // address of the node that sent the message
 *     int id;
 *     int ttl;
 * }
 * </pre>
 */
class TransactionsMsg : public ::omnetpp::cPacket
{
  protected:
    Transactions transactions;
    TransportAddress senderAddress;
    int id;
    int ttl;

  private:
    void copy(const TransactionsMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TransactionsMsg&);

  public:
    TransactionsMsg(const char *name=nullptr, short kind=0);
    TransactionsMsg(const TransactionsMsg& other);
    virtual ~TransactionsMsg();
    TransactionsMsg& operator=(const TransactionsMsg& other);
    virtual TransactionsMsg *dup() const override {return new TransactionsMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual Transactions& getTransactions();
    virtual const Transactions& getTransactions() const {return const_cast<TransactionsMsg*>(this)->getTransactions();}
    virtual void setTransactions(const Transactions& transactions);
    virtual TransportAddress& getSenderAddress();
    virtual const TransportAddress& getSenderAddress() const {return const_cast<TransactionsMsg*>(this)->getSenderAddress();}
    virtual void setSenderAddress(const TransportAddress& senderAddress);
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getTtl() const;
    virtual void setTtl(int ttl);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransactionsMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransactionsMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRANSACTIONSMSG_M_H

